config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sessions, only:[:new,:create,:destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :favorites, only:[:create,:destroy]
  resources :contacts
  resources :users, only:[:new,:create,:show,:edit,:update] do
    get :favorites, on: :member
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :profile, length: { maximum: 250 }
  mount_uploader :image, ImageUploader
  validates :name,  presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 },
             format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :image, presence: true
  validates :profile, presence: true
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :user_favorites, through: :favorites, source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if logged_in? == false
      flash[:notice] = ('ログインしてください')
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:show, :new, :edit, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all.order("id DESC")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)
      if params[:back]
        render :new
      else
        respond_to do |format|
          if @blog.save
            format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
            format.json { render :show, status: :created, location: @blog }
          else
            format.html { render :new }
            format.json { render json: @blog.errors, status: :unprocessable_entity }
          end
        end
      end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :image_cache)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to blogs_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update ]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "更新しました!"
    else
      render :edit, notice: "更新できませんでした"
    end
  end

  def favorites
    @favorite = current_user.user_favorites
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache, :profile)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: choose_new_or_edit ) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<div class="form_template">
  <h1>以下の内容でよろしいですか？</h1>
  <%= form_with(model: @blog, local: true) do |form| %>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.hidden_field :title %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <h1>title:<%= @blog.title %></h1>
    <p>content:<%= @blog.content %></p>

    <%= form.submit %>

    <%= form.submit 'BACK', name: 'back' , class:"btn btn-outline-info" %>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<div class="form_template">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path, class: "btn btn-outline-info" %>
</div>

app/views/blogs/index.html.erb
<div class="wrap">
    <% @blogs.each do |blog| %>
      <div class="item">
        <% if blog.image.url.present? %>
          <%= link_to blog_path(blog.id) do %>
            <div class="uploaded_image">
              <%= image_tag blog.image.url %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/blogs/new.html.erb
<div class="form_template">
  <h1>New Post</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to image_tag("back.png"), blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="split">
  <div class="split-item split-left">
    <div class="split-left__inner">
      <div class="content_image">
        <%= image_tag @blog.image.url %>
      </div>
      <div class="edit_and_back">
        <% if current_user == @blog.user %>
          <%= link_to image_tag("edit.png"), edit_blog_path(@blog) %>
          <%= link_to image_tag("delete_on.png"), blog_path(@blog), method: :delete, data: { confirm: '本当に消しますか？' } %>
        <% end %>
        <% unless @blog.user_id == current_user.id %>
          <% if @favorite.present? %>
            <%= link_to '♥', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to '♡', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="split-item split-right">
    <div class="split-right__inner">
      <div class="title_and_content">
        <h1><strong><%= @blog.title %></strong></h1>
        <div class="uploaded_user">
          uploaded by
          <%= link_to image_tag(@blog.user.image.url),user_path(@blog.user_id)  %>
        </div>
        <p>
          <%= @blog.content %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bootstrap
      </a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/contacts/new.html.erb
<div class="form_template">
  <h1>New Contact</h1>

  <%= render 'form', contact: @contact %>

  <%= link_to image_tag("back.png"), blogs_path %>
</div>

app/views/contacts/show.html.erb
<div class="form_template">
  <p>
    <strong>Name:</strong>
    <%= @contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @contact.email %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @contact.content %>
  </p>
  <%= link_to image_tag("back.png"), blogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insta_Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="wrapper">
    <div class="left_body">
      <body>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
        <%= yield %>
      </body>
    </div>
    <div class="right_body">
      <div class="menu_bar">
        <% if logged_in? %>
          <ul>
            <div id="user_image">
              <li><%= link_to user_path(current_user.id) do %>
                    <%= image_tag current_user.image.url %>
                  <% end %>
              </li>
              <li><%= current_user.name %></li>
            </div>
            <li><%= link_to image_tag("home.png"), blogs_path %></li>
            <li>HOME</li>
            <li><%= link_to image_tag("blog_new.png"), new_blog_path %></li>
            <li>POST</li>
            <li><%= link_to image_tag("favorite.png"), favorites_user_path(current_user.id) %></li>
            <li>FAVORITE</li>
            <li><%= link_to image_tag("new_contact.png"), new_contact_path %></li>
            <li>CONTACT</li>
            <li><%= link_to image_tag("log_out.png"), session_path(current_user.id), method: :delete %></li>
            <li>LOG OUT</li>

        <% else %>
          <ul>
            <li><%= link_to image_tag("home.png"), blogs_path %></li>
            <li>HOME</li>
            <li><%= link_to image_tag("sign_in.png"), new_user_path %></li>
            <li>SIGN IN</li>
            <li><%= link_to image_tag("log_in.png"), new_session_path %></li>
            <li>LOG IN</li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>

</html>

app/views/users/_form.html.erb
<div class="form_template">

  <%= form_with(model: user, local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.label :profile %>
    <%= f.text_area :profile %>
    <%= f.submit %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="form_template">
  <%= render 'form', user: @user %>
</div>

app/views/users/favorites.html.erb
<h1>ふぁぼした投稿一覧</h1>
 <div class="fav_image">
  <% @favorite.each do |fav| %>
    <%= image_tag(fav.image.url) %>
  <% end %>
 </div>

app/views/users/new.html.erb
<div class="form_template">
  <h1>Sign Up</h1>
    <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="form_template">
  <h1><%= @user.name %>のページ</h1>
    <div class="user_profile_image">
      <%= image_tag @user.image.url %>
    </div>

    <p>email:<%= @user.email %></p>
    <p>profile:<%= @user.profile %></p>
  <% if current_user == @user %>
    <%= link_to image_tag("edit.png"), edit_user_path %>
  <% end %>
  <%= link_to 'Back', blogs_path, class: "btn btn-outline-info" %>
</div>